// Mock Data for E-Commerce Store
// Comprehensive product catalog with multiple items per category

export const mockCategories = [
    { _id: "cat1", name: "Electronics", icon: "📱", image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=200" },
    { _id: "cat2", name: "Fashion", icon: "👕", image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=200" },
    { _id: "cat3", name: "Home & Furniture", icon: "🏠", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=200" },
    { _id: "cat4", name: "Appliances", icon: "🔌", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200" },
    { _id: "cat5", name: "Beauty & Health", icon: "💄", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200" },
    { _id: "cat6", name: "Sports", icon: "⚽", image: "https://images.unsplash.com/photo-1461896836934- voices?w=200" },
    { _id: "cat7", name: "Books", icon: "📚", image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=200" },
    { _id: "cat8", name: "Gaming", icon: "🎮", image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=200" },
];

export const mockProducts = [
    // Electronics - 8 items
    {
        _id: "prod1",
        name: "iPhone 15 Pro Max 256GB - Natural Titanium",
        image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400",
        description: "Apple iPhone 15 Pro Max with A17 Pro chip, titanium design, and advanced camera system.",
        brand: "Apple",
        category: "cat1",
        price: 1199,
        originalPrice: 1299,
        countInStock: 25,
        rating: 4.8,
        numReviews: 2847,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 8,
        reviews: [],
    },
    {
        _id: "prod2",
        name: "Samsung Galaxy S24 Ultra 512GB - Titanium Black",
        image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
        description: "Samsung Galaxy S24 Ultra with Galaxy AI, S Pen, and 200MP camera.",
        brand: "Samsung",
        category: "cat1",
        price: 1099,
        originalPrice: 1299,
        countInStock: 18,
        rating: 4.6,
        numReviews: 1923,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 15,
        reviews: [],
    },
    {
        _id: "prod3",
        name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
        image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400",
        description: "Industry-leading noise cancellation with 30-hour battery life.",
        brand: "Sony",
        category: "cat1",
        price: 349,
        originalPrice: 399,
        countInStock: 42,
        rating: 4.7,
        numReviews: 5621,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 13,
        reviews: [],
    },
    {
        _id: "prod4",
        name: "MacBook Pro 14-inch M3 Pro 18GB RAM",
        image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
        description: "Apple MacBook Pro with M3 Pro chip, Liquid Retina XDR display.",
        brand: "Apple",
        category: "cat1",
        price: 1999,
        originalPrice: 2199,
        countInStock: 12,
        rating: 4.9,
        numReviews: 892,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 4,
        discount: 9,
        reviews: [],
    },
    {
        _id: "prod5",
        name: "Apple Watch Series 9 GPS 45mm",
        image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400",
        description: "Advanced health features with blood oxygen and ECG monitoring.",
        brand: "Apple",
        category: "cat1",
        price: 429,
        originalPrice: 459,
        countInStock: 35,
        rating: 4.6,
        numReviews: 6742,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 7,
        reviews: [],
    },
    {
        _id: "prod6",
        name: "iPad Pro 12.9-inch M2 256GB WiFi",
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
        description: "Apple iPad Pro with M2 chip and Liquid Retina XDR display.",
        brand: "Apple",
        category: "cat1",
        price: 1099,
        originalPrice: 1199,
        countInStock: 20,
        rating: 4.8,
        numReviews: 3421,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 8,
        reviews: [],
    },
    {
        _id: "prod7",
        name: "Canon EOS R6 Mark II Mirrorless Camera",
        image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400",
        description: "24.2MP full-frame sensor with 40fps continuous shooting.",
        brand: "Canon",
        category: "cat1",
        price: 2499,
        originalPrice: 2799,
        countInStock: 6,
        rating: 4.8,
        numReviews: 892,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 11,
        reviews: [],
    },
    {
        _id: "prod8",
        name: "AirPods Pro 2nd Generation with USB-C",
        image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400",
        description: "Active Noise Cancellation, Transparency mode, Personalized Spatial Audio.",
        brand: "Apple",
        category: "cat1",
        price: 229,
        originalPrice: 249,
        countInStock: 50,
        rating: 4.7,
        numReviews: 12847,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 8,
        reviews: [],
    },

    // Fashion - 8 items
    {
        _id: "prod9",
        name: "Nike Air Max 270 Running Shoes - Black/White",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        description: "Lightweight running shoes with Max Air unit for all-day comfort.",
        brand: "Nike",
        category: "cat2",
        price: 129,
        originalPrice: 160,
        countInStock: 85,
        rating: 4.5,
        numReviews: 12847,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 19,
        reviews: [],
    },
    {
        _id: "prod10",
        name: "Levi's 501 Original Fit Jeans - Dark Wash",
        image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
        description: "The iconic straight fit jean with signature button fly.",
        brand: "Levi's",
        category: "cat2",
        price: 69,
        originalPrice: 89,
        countInStock: 120,
        rating: 4.4,
        numReviews: 8932,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 4,
        discount: 22,
        reviews: [],
    },
    {
        _id: "prod11",
        name: "Adidas Ultraboost 23 Running Shoes",
        image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
        description: "Responsive Boost cushioning for incredible energy return.",
        brand: "Adidas",
        category: "cat2",
        price: 159,
        originalPrice: 190,
        countInStock: 45,
        rating: 4.6,
        numReviews: 7823,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 16,
        reviews: [],
    },
    {
        _id: "prod12",
        name: "Ralph Lauren Polo Classic Fit Shirt",
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400",
        description: "Iconic polo shirt in breathable cotton mesh.",
        brand: "Ralph Lauren",
        category: "cat2",
        price: 89,
        originalPrice: 110,
        countInStock: 60,
        rating: 4.5,
        numReviews: 4521,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 4,
        discount: 19,
        reviews: [],
    },
    {
        _id: "prod13",
        name: "Ray-Ban Aviator Classic Sunglasses",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
        description: "Iconic aviator style with crystal green lenses.",
        brand: "Ray-Ban",
        category: "cat2",
        price: 161,
        originalPrice: 189,
        countInStock: 30,
        rating: 4.7,
        numReviews: 9823,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 15,
        reviews: [],
    },
    {
        _id: "prod14",
        name: "Tommy Hilfiger Essential Down Jacket",
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        description: "Warm and lightweight down jacket with signature branding.",
        brand: "Tommy Hilfiger",
        category: "cat2",
        price: 199,
        originalPrice: 249,
        countInStock: 25,
        rating: 4.4,
        numReviews: 3421,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 5,
        discount: 20,
        reviews: [],
    },
    {
        _id: "prod15",
        name: "Fossil Gen 6 Hybrid Smartwatch",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
        description: "Classic watch design with smart features.",
        brand: "Fossil",
        category: "cat2",
        price: 179,
        originalPrice: 229,
        countInStock: 40,
        rating: 4.3,
        numReviews: 2134,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 22,
        reviews: [],
    },
    {
        _id: "prod16",
        name: "H&M Regular Fit Cotton T-Shirt Pack of 3",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
        description: "Essential cotton t-shirts in neutral colors.",
        brand: "H&M",
        category: "cat2",
        price: 29,
        originalPrice: 39,
        countInStock: 200,
        rating: 4.2,
        numReviews: 15673,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 4,
        discount: 26,
        reviews: [],
    },

    // Home & Furniture - 6 items
    {
        _id: "prod17",
        name: "Modern L-Shaped Sectional Sofa - Grey",
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
        description: "Contemporary sectional sofa with premium fabric upholstery.",
        brand: "IKEA",
        category: "cat3",
        price: 899,
        originalPrice: 1199,
        countInStock: 8,
        rating: 4.3,
        numReviews: 456,
        isFeatured: true,
        isAssured: false,
        freeDelivery: false,
        deliveryDays: 7,
        discount: 25,
        reviews: [],
    },
    {
        _id: "prod18",
        name: "Ergonomic Office Chair with Lumbar Support",
        image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400",
        description: "Adjustable office chair with breathable mesh back.",
        brand: "Herman Miller",
        category: "cat3",
        price: 449,
        originalPrice: 549,
        countInStock: 15,
        rating: 4.6,
        numReviews: 2341,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 5,
        discount: 18,
        reviews: [],
    },
    {
        _id: "prod19",
        name: "King Size Memory Foam Mattress 12-inch",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400",
        description: "Premium memory foam mattress with cooling gel technology.",
        brand: "Casper",
        category: "cat3",
        price: 799,
        originalPrice: 999,
        countInStock: 10,
        rating: 4.7,
        numReviews: 5678,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 7,
        discount: 20,
        reviews: [],
    },
    {
        _id: "prod20",
        name: "Smart LED Floor Lamp with Remote",
        image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400",
        description: "Dimmable LED floor lamp with color temperature control.",
        brand: "Philips",
        category: "cat3",
        price: 89,
        originalPrice: 119,
        countInStock: 35,
        rating: 4.4,
        numReviews: 1234,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 25,
        reviews: [],
    },
    {
        _id: "prod21",
        name: "Minimalist Wooden Coffee Table",
        image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400",
        description: "Scandinavian design coffee table with storage shelf.",
        brand: "West Elm",
        category: "cat3",
        price: 299,
        originalPrice: 399,
        countInStock: 12,
        rating: 4.5,
        numReviews: 876,
        isFeatured: false,
        isAssured: true,
        freeDelivery: false,
        deliveryDays: 6,
        discount: 25,
        reviews: [],
    },
    {
        _id: "prod22",
        name: "Velvet Accent Chair - Emerald Green",
        image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400",
        description: "Luxurious velvet accent chair with gold legs.",
        brand: "Article",
        category: "cat3",
        price: 349,
        originalPrice: 449,
        countInStock: 8,
        rating: 4.6,
        numReviews: 543,
        isFeatured: true,
        isAssured: true,
        freeDelivery: false,
        deliveryDays: 5,
        discount: 22,
        reviews: [],
    },

    // Appliances - 6 items
    {
        _id: "prod23",
        name: "Dyson V15 Detect Cordless Vacuum",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
        description: "Most powerful cordless vacuum with laser dust detection.",
        brand: "Dyson",
        category: "cat4",
        price: 649,
        originalPrice: 749,
        countInStock: 22,
        rating: 4.7,
        numReviews: 3421,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 13,
        reviews: [],
    },
    {
        _id: "prod24",
        name: "Instant Pot Duo Plus 9-in-1 Pressure Cooker",
        image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
        description: "Multi-use programmable pressure cooker, 6 Qt capacity.",
        brand: "Instant Pot",
        category: "cat4",
        price: 89,
        originalPrice: 119,
        countInStock: 50,
        rating: 4.8,
        numReviews: 45892,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 25,
        reviews: [],
    },
    {
        _id: "prod25",
        name: "LG French Door Refrigerator 28 cu ft",
        image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400",
        description: "Smart refrigerator with InstaView Door-in-Door.",
        brand: "LG",
        category: "cat4",
        price: 2199,
        originalPrice: 2599,
        countInStock: 5,
        rating: 4.5,
        numReviews: 1234,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 7,
        discount: 15,
        reviews: [],
    },
    {
        _id: "prod26",
        name: "KitchenAid Stand Mixer Artisan Series",
        image: "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=400",
        description: "Iconic tilt-head stand mixer with 5-quart bowl.",
        brand: "KitchenAid",
        category: "cat4",
        price: 379,
        originalPrice: 449,
        countInStock: 18,
        rating: 4.9,
        numReviews: 8976,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 16,
        reviews: [],
    },
    {
        _id: "prod27",
        name: "Breville Barista Express Espresso Machine",
        image: "https://images.unsplash.com/photo-1517142089942-ba376ce32a2e?w=400",
        description: "Professional espresso machine with built-in grinder.",
        brand: "Breville",
        category: "cat4",
        price: 599,
        originalPrice: 699,
        countInStock: 12,
        rating: 4.6,
        numReviews: 4532,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 4,
        discount: 14,
        reviews: [],
    },
    {
        _id: "prod28",
        name: "Ninja Foodi Smart XL Grill",
        image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400",
        description: "6-in-1 indoor grill with smart cook system.",
        brand: "Ninja",
        category: "cat4",
        price: 249,
        originalPrice: 299,
        countInStock: 25,
        rating: 4.5,
        numReviews: 6789,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 17,
        reviews: [],
    },

    // Beauty & Health - 6 items
    {
        _id: "prod29",
        name: "Dyson Airwrap Complete Styler",
        image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400",
        description: "Multi-styler with Coanda air technology for all hair types.",
        brand: "Dyson",
        category: "cat5",
        price: 549,
        originalPrice: 599,
        countInStock: 15,
        rating: 4.7,
        numReviews: 8976,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 8,
        reviews: [],
    },
    {
        _id: "prod30",
        name: "Olaplex Hair Perfector No 3 Treatment",
        image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400",
        description: "Bond building treatment for damaged hair.",
        brand: "Olaplex",
        category: "cat5",
        price: 28,
        originalPrice: 30,
        countInStock: 80,
        rating: 4.6,
        numReviews: 23456,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 7,
        reviews: [],
    },
    {
        _id: "prod31",
        name: "La Mer Crème de la Mer Moisturizing Cream",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
        description: "Luxury moisturizer with Miracle Broth.",
        brand: "La Mer",
        category: "cat5",
        price: 345,
        originalPrice: 380,
        countInStock: 20,
        rating: 4.8,
        numReviews: 5432,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 9,
        reviews: [],
    },
    {
        _id: "prod32",
        name: "Oral-B iO Series 9 Electric Toothbrush",
        image: "https://images.unsplash.com/photo-1559056199-5c3a5a5d5f3b?w=400",
        description: "Smart electric toothbrush with AI-powered coaching.",
        brand: "Oral-B",
        category: "cat5",
        price: 249,
        originalPrice: 299,
        countInStock: 30,
        rating: 4.5,
        numReviews: 7654,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 17,
        reviews: [],
    },
    {
        _id: "prod33",
        name: "Theragun Elite Massage Gun",
        image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
        description: "Deep tissue massage with QuietForce Technology.",
        brand: "Therabody",
        category: "cat5",
        price: 349,
        originalPrice: 399,
        countInStock: 18,
        rating: 4.7,
        numReviews: 4321,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 13,
        reviews: [],
    },
    {
        _id: "prod34",
        name: "Fitbit Charge 6 Advanced Fitness Tracker",
        image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400",
        description: "Advanced health metrics with GPS and heart rate.",
        brand: "Fitbit",
        category: "cat5",
        price: 139,
        originalPrice: 159,
        countInStock: 45,
        rating: 4.4,
        numReviews: 9876,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 13,
        reviews: [],
    },

    // Books - 4 items
    {
        _id: "prod35",
        name: "The Psychology of Money - Morgan Housel",
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        description: "Timeless lessons on wealth, greed, and happiness.",
        brand: "Harriman House",
        category: "cat7",
        price: 14,
        originalPrice: 19,
        countInStock: 200,
        rating: 4.8,
        numReviews: 45892,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 26,
        reviews: [],
    },
    {
        _id: "prod36",
        name: "Atomic Habits - James Clear",
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        description: "An easy way to build good habits and break bad ones.",
        brand: "Avery",
        category: "cat7",
        price: 16,
        originalPrice: 21,
        countInStock: 180,
        rating: 4.9,
        numReviews: 78234,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 24,
        reviews: [],
    },
    {
        _id: "prod37",
        name: "Deep Work - Cal Newport",
        image: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=400",
        description: "Rules for focused success in a distracted world.",
        brand: "Grand Central",
        category: "cat7",
        price: 15,
        originalPrice: 18,
        countInStock: 150,
        rating: 4.6,
        numReviews: 23456,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 17,
        reviews: [],
    },
    {
        _id: "prod38",
        name: "Thinking, Fast and Slow - Daniel Kahneman",
        image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400",
        description: "How we think and make decisions.",
        brand: "Farrar",
        category: "cat7",
        price: 17,
        originalPrice: 22,
        countInStock: 120,
        rating: 4.7,
        numReviews: 34567,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 23,
        reviews: [],
    },

    // Gaming - 6 items
    {
        _id: "prod39",
        name: "PlayStation 5 Console - Disc Edition",
        image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400",
        description: "Next-gen gaming with ultra-high speed SSD.",
        brand: "Sony",
        category: "cat8",
        price: 499,
        originalPrice: 549,
        countInStock: 15,
        rating: 4.9,
        numReviews: 28471,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 9,
        reviews: [],
    },
    {
        _id: "prod40",
        name: "Xbox Series X Console",
        image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400",
        description: "Most powerful Xbox ever with 12 teraflops of power.",
        brand: "Microsoft",
        category: "cat8",
        price: 479,
        originalPrice: 499,
        countInStock: 12,
        rating: 4.8,
        numReviews: 19876,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 4,
        reviews: [],
    },
    {
        _id: "prod41",
        name: "Nintendo Switch OLED Model",
        image: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400",
        description: "Vibrant 7-inch OLED screen with enhanced audio.",
        brand: "Nintendo",
        category: "cat8",
        price: 349,
        originalPrice: 359,
        countInStock: 30,
        rating: 4.7,
        numReviews: 15432,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 3,
        reviews: [],
    },
    {
        _id: "prod42",
        name: "Razer BlackWidow V4 Pro Mechanical Keyboard",
        image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400",
        description: "Premium mechanical keyboard with customizable RGB.",
        brand: "Razer",
        category: "cat8",
        price: 229,
        originalPrice: 279,
        countInStock: 25,
        rating: 4.6,
        numReviews: 5678,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 18,
        reviews: [],
    },
    {
        _id: "prod43",
        name: "Logitech G Pro X Superlight Mouse",
        image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
        description: "Ultra-lightweight wireless gaming mouse.",
        brand: "Logitech",
        category: "cat8",
        price: 149,
        originalPrice: 159,
        countInStock: 40,
        rating: 4.8,
        numReviews: 8765,
        isFeatured: false,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 2,
        discount: 6,
        reviews: [],
    },
    {
        _id: "prod44",
        name: "SteelSeries Arctis Nova Pro Wireless Headset",
        image: "https://images.unsplash.com/photo-1599669454699-248893623440?w=400",
        description: "Hi-Fi gaming headset with Active Noise Cancellation.",
        brand: "SteelSeries",
        category: "cat8",
        price: 329,
        originalPrice: 349,
        countInStock: 20,
        rating: 4.7,
        numReviews: 4321,
        isFeatured: true,
        isAssured: true,
        freeDelivery: true,
        deliveryDays: 3,
        discount: 6,
        reviews: [],
    },
];

export const mockBanners = [
    {
        id: 1,
        title: "Big Billion Days Sale",
        subtitle: "Up to 80% Off on Top Brands",
        image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200",
        gradient: "from-blue-600 to-purple-600",
        link: "/shop",
    },
    {
        id: 2,
        title: "Electronics Fest",
        subtitle: "Latest Gadgets at Best Prices",
        image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1200",
        gradient: "from-orange-500 to-red-500",
        link: "/shop?category=cat1",
    },
    {
        id: 3,
        title: "Fashion Week Special",
        subtitle: "Trending Styles - Extra 20% Off",
        image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200",
        gradient: "from-pink-500 to-rose-500",
        link: "/shop?category=cat2",
    },
    {
        id: 4,
        title: "Home Makeover Sale",
        subtitle: "Transform Your Space - Up to 50% Off",
        image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200",
        gradient: "from-green-500 to-teal-500",
        link: "/shop?category=cat3",
    },
];

// Helper functions
export const getProductsByCategory = (categoryId) => {
    return mockProducts.filter(p => p.category === categoryId);
};

export const getFeaturedProducts = () => {
    return mockProducts.filter(p => p.isFeatured);
};

export const searchProducts = (query) => {
    const lowerQuery = query.toLowerCase();
    return mockProducts.filter(
        p => p.name.toLowerCase().includes(lowerQuery) ||
            p.brand.toLowerCase().includes(lowerQuery) ||
            p.description.toLowerCase().includes(lowerQuery)
    );
};

export const getProductById = (id) => {
    return mockProducts.find(p => p._id === id);
};
